# Generated by Django 3.0.3 on 2020-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesent',
            name='message_body_text',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
