# Generated by Django 3.0.3 on 2020-02-09 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messagesent_message_body_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebody',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagebody',
            name='message_type',
            field=models.CharField(choices=[('send', 'Send'), ('respond_bad', 'Respond to Bad Message'), ('respond_good', 'Respond to Good Message')], default='send', max_length=100),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='message_from_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='message_service_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='message_to_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='messagebody',
            name='message',
            field=models.CharField(max_length=239),
        ),
        migrations.CreateModel(
            name='MessageReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(blank=True, max_length=1024, null=True)),
                ('message_from_number', models.CharField(blank=True, max_length=16, null=True)),
                ('message_from_city', models.CharField(blank=True, max_length=64, null=True)),
                ('message_from_state', models.CharField(blank=True, max_length=2, null=True)),
                ('message_from_zip', models.CharField(blank=True, max_length=16, null=True)),
                ('message_from_country', models.CharField(blank=True, max_length=32, null=True)),
                ('message_to_number', models.CharField(blank=True, max_length=16, null=True)),
                ('message_to_city', models.CharField(blank=True, max_length=64, null=True)),
                ('message_to_state', models.CharField(blank=True, max_length=2, null=True)),
                ('message_to_zip', models.CharField(blank=True, max_length=16, null=True)),
                ('message_to_country', models.CharField(blank=True, max_length=32, null=True)),
                ('account_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('message_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('number_of_segments', models.IntegerField(blank=True, null=True)),
                ('sms_message_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('sms_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_response_sent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_received', to='api.MessageBody')),
            ],
        ),
    ]
