# Generated by Django 3.0.3 on 2020-02-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200209_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagebody',
            options={'verbose_name': 'Message Body', 'verbose_name_plural': 'Message Bodies'},
        ),
        migrations.AlterModelOptions(
            name='messagereceive',
            options={'verbose_name': 'Message Received', 'verbose_name_plural': 'Messages Received'},
        ),
        migrations.AlterModelOptions(
            name='messagesent',
            options={'verbose_name': 'Message Sent', 'verbose_name_plural': 'Messages Sent'},
        ),
        migrations.RenameField(
            model_name='messagereceive',
            old_name='message_body',
            new_name='message_received',
        ),
        migrations.RenameField(
            model_name='messagesent',
            old_name='message_body_text',
            new_name='message_sent',
        ),
    ]
