# Generated by Django 3.0.3 on 2020-04-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200209_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereceive',
            name='message_responded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_responded_to', to='api.MessageSent'),
        ),
        migrations.AddField(
            model_name='messagesent',
            name='sent_type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('website', 'Website')], default='twilio', max_length=32),
        ),
    ]
