# Generated by Django 3.0.3 on 2020-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails/'),
        ),
    ]
