# Generated by Django 3.0.3 on 2020-05-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_picture_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='thumbnail',
        ),
    ]
